spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase
  task:
    scheduling:
      thread-name-prefix: scheduled-task-
      pool:
        size: '1'
  application:
    name: jenkins-console
  main:
    banner-mode: 'off'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
server:
  port: '9210'
project:
  name: deneme
